/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {
      type: 'category',
      label: 'Connect with us',
      items: [
        {
          type: 'link',
          label: 'Twitter',
          href: 'https://twitter.com/gas_pad_io',
        },
        {
          type: 'link',
          label: 'Telegram',
          href: 'https://t.me/gaspadbbc',
        },
        {
          type: 'link',
          label: 'Discord',
          href: 'https://discord.gg/RukjxxCmE2',
        },
     
        {
          type: 'link',
          label: 'Medium',
          href: 'https://medium.com/@gaspadd.io',
        },
        
      
      ],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      items: [
        {
          type: 'link',
          label: 'Swap',
          href: 'https://flamez.io/',
        },
        {
          type: 'link',
          label: 'Launch Pad',
          href: 'https://gaspad.io/',
        },
        {
          type: 'link',
          label: 'NFT Marketplace',
          href: 'https://fireflys.art/',
        },
      
      ],
    },
  ],
};

module.exports = sidebars;